-- Structured skill schema v2.
-- Backward-compatible extension for AI-friendly rule execution.

begin;

alter table master.m_skill
  add column if not exists skill_type text not null default 'active_or_passive',
  add column if not exists target_rule text not null default 'unspecified',
  add column if not exists effect_summary_type text not null default 'scripted',
  add column if not exists proc_chance numeric(5,4),
  add column if not exists duration_turns integer,
  add column if not exists script_hook text,
  add column if not exists parse_status text not null default 'raw_text',
  add column if not exists params_json jsonb not null default '{}'::jsonb;

create table if not exists master.m_skill_effect (
  skill_effect_id bigint generated by default as identity primary key,
  skill_id bigint not null references master.m_skill(skill_id) on delete cascade,
  effect_order smallint not null default 1,
  effect_type text not null,
  target_rule text not null default 'unspecified',
  trigger_timing text,
  proc_chance numeric(5,4),
  duration_turns integer,
  radius integer,
  value_num numeric,
  value_text text,
  params_json jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint m_skill_effect_order_chk check (effect_order >= 1),
  constraint m_skill_effect_proc_chance_chk check (proc_chance is null or (proc_chance >= 0 and proc_chance <= 1)),
  constraint m_skill_effect_duration_turns_chk check (duration_turns is null or duration_turns >= 0),
  constraint m_skill_effect_radius_chk check (radius is null or radius >= 0)
);

create unique index if not exists m_skill_effect_skill_order_uq
  on master.m_skill_effect(skill_id, effect_order);

create index if not exists m_skill_effect_lookup_idx
  on master.m_skill_effect(effect_type, target_rule, trigger_timing);

create index if not exists m_skill_script_hook_idx
  on master.m_skill(script_hook)
  where script_hook is not null;

commit;
