-- Extend stage domain: clear conditions and normalized rewards.

begin;

alter table master.m_stage
  add column if not exists stage_category text not null default 'normal',
  add column if not exists clear_condition_type text not null default 'defeat_boss',
  add column if not exists clear_condition_params jsonb not null default '{}'::jsonb,
  add column if not exists recommended_power integer,
  add column if not exists stamina_cost integer not null default 0;

alter table master.m_stage
  add constraint m_stage_stage_category_chk
    check (stage_category in ('normal', 'tutorial', 'challenge', 'event'));

alter table master.m_stage
  add constraint m_stage_clear_condition_type_chk
    check (clear_condition_type in ('defeat_boss', 'defeat_all', 'survive_turns', 'reach_target'));

alter table master.m_stage
  add constraint m_stage_recommended_power_chk
    check (recommended_power is null or recommended_power >= 0);

alter table master.m_stage
  add constraint m_stage_stamina_cost_chk
    check (stamina_cost >= 0);

create table if not exists master.m_reward (
  reward_id bigint generated by default as identity primary key,
  reward_code text not null unique,
  reward_type text not null,
  reward_name text not null,
  piece_id bigint references master.m_piece(piece_id),
  item_code text,
  is_active boolean not null default true,
  published_at timestamptz,
  unpublished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint m_reward_type_chk
    check (reward_type in ('piece', 'item', 'currency', 'ticket')),
  constraint m_reward_piece_item_xor_chk
    check (
      (reward_type = 'piece' and piece_id is not null and item_code is null)
      or
      (reward_type <> 'piece' and piece_id is null and item_code is not null)
    ),
  constraint m_reward_publish_window_chk
    check (unpublished_at is null or published_at is null or unpublished_at > published_at)
);

create table if not exists master.m_stage_reward (
  stage_reward_id bigint generated by default as identity primary key,
  stage_id bigint not null references master.m_stage(stage_id) on delete cascade,
  reward_id bigint not null references master.m_reward(reward_id),
  reward_timing text not null,
  quantity integer not null default 1,
  drop_rate numeric(5,4),
  sort_order smallint not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint m_stage_reward_timing_chk
    check (reward_timing in ('first_clear', 'clear', 'drop', 'mission')),
  constraint m_stage_reward_quantity_chk
    check (quantity >= 1),
  constraint m_stage_reward_drop_rate_chk
    check (drop_rate is null or (drop_rate >= 0 and drop_rate <= 1)),
  constraint m_stage_reward_sort_order_chk
    check (sort_order >= 1),
  constraint m_stage_reward_unique_row_uq
    unique (stage_id, reward_id, reward_timing, sort_order)
);

create index if not exists m_stage_reward_stage_idx
  on master.m_stage_reward(stage_id, reward_timing, sort_order);

create index if not exists m_stage_reward_reward_idx
  on master.m_stage_reward(reward_id);

commit;
