begin;

create schema if not exists game;

create table if not exists game.games (
  game_id uuid primary key default gen_random_uuid(),
  player_id uuid not null references public.players(id) on delete restrict,
  stage_id bigint references master.m_stage(stage_id) on delete set null,
  status text not null default 'in_progress',
  result text,
  winner_side text,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists game.positions (
  game_id uuid primary key references game.games(game_id) on delete cascade,
  board_state jsonb not null,
  hands jsonb not null default '{}'::jsonb,
  side_to_move text not null,
  turn_number integer not null default 1,
  move_count integer not null default 0,
  sfen text,
  state_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists game.moves (
  move_id bigint generated by default as identity primary key,
  game_id uuid not null references game.games(game_id) on delete cascade,
  move_no integer not null,
  actor_side text not null,
  from_row integer,
  from_col integer,
  to_row integer not null,
  to_col integer not null,
  piece_code text not null,
  promote boolean not null default false,
  drop_piece_code text,
  captured_piece_code text,
  notation text,
  thought_ms integer,
  created_at timestamptz not null default now(),
  constraint moves_game_move_no_uq unique (game_id, move_no)
);

create table if not exists game.ai_inference_logs (
  inference_id bigint generated by default as identity primary key,
  game_id uuid not null references game.games(game_id) on delete cascade,
  move_no integer not null,
  engine_version text not null,
  engine_config jsonb not null,
  request_payload jsonb not null,
  response_payload jsonb not null,
  selected_move text,
  eval_cp integer,
  searched_nodes bigint,
  search_depth integer,
  think_ms integer not null,
  created_at timestamptz not null default now()
);

commit;
