-- Player deck system: owned pieces + saved decks with board placements.
-- player_deck_placements mirrors master.m_stage_initial_placement in structure.

begin;

-- -----------------------------------------------------------------------
-- 1. player_owned_pieces
--    PK: (player_id, piece_id) — a player owns each piece at most once.
-- -----------------------------------------------------------------------
create table if not exists public.player_owned_pieces (
  player_id   uuid    not null references public.players(id) on delete cascade,
  piece_id    bigint  not null references master.m_piece(piece_id),
  acquired_at timestamptz not null default now(),
  source      text    not null default 'initial',
  primary key (player_id, piece_id),
  constraint player_owned_pieces_source_chk
    check (source in ('gacha', 'shop', 'initial'))
);

create index if not exists player_owned_pieces_player_idx
  on public.player_owned_pieces(player_id);

alter table public.player_owned_pieces enable row level security;

create policy "player_owned_pieces: self read"
  on public.player_owned_pieces for select
  using (auth.uid() = player_id);

create policy "player_owned_pieces: self insert"
  on public.player_owned_pieces for insert
  with check (auth.uid() = player_id);

create policy "player_owned_pieces: self delete"
  on public.player_owned_pieces for delete
  using (auth.uid() = player_id);

-- -----------------------------------------------------------------------
-- 2. player_decks
--    A player can have multiple named decks.
-- -----------------------------------------------------------------------
create table if not exists public.player_decks (
  deck_id     bigint      generated by default as identity primary key,
  player_id   uuid        not null references public.players(id) on delete cascade,
  name        text        not null default 'マイデッキ',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint player_decks_name_len_chk check (char_length(name) between 1 and 40)
);

create index if not exists player_decks_player_idx
  on public.player_decks(player_id);

alter table public.player_decks enable row level security;

create policy "player_decks: self read"
  on public.player_decks for select
  using (auth.uid() = player_id);

create policy "player_decks: self insert"
  on public.player_decks for insert
  with check (auth.uid() = player_id);

create policy "player_decks: self update"
  on public.player_decks for update
  using (auth.uid() = player_id);

create policy "player_decks: self delete"
  on public.player_decks for delete
  using (auth.uid() = player_id);

-- -----------------------------------------------------------------------
-- 3. player_deck_placements
--    One row per cell. Same shape as master.m_stage_initial_placement.
--    PK: (deck_id, row_no, col_no) — one piece per cell.
-- -----------------------------------------------------------------------
create table if not exists public.player_deck_placements (
  deck_id  bigint  not null references public.player_decks(deck_id) on delete cascade,
  row_no   integer not null,
  col_no   integer not null,
  piece_id bigint  not null references master.m_piece(piece_id),
  primary key (deck_id, row_no, col_no),
  constraint player_deck_placements_row_chk  check (row_no between 0 and 8),
  constraint player_deck_placements_col_chk  check (col_no between 0 and 8)
);

create index if not exists player_deck_placements_deck_idx
  on public.player_deck_placements(deck_id);

-- RLS is enforced via deck ownership (join to player_decks).
alter table public.player_deck_placements enable row level security;

create policy "player_deck_placements: self read"
  on public.player_deck_placements for select
  using (
    exists (
      select 1 from public.player_decks d
      where d.deck_id = player_deck_placements.deck_id
        and d.player_id = auth.uid()
    )
  );

create policy "player_deck_placements: self insert"
  on public.player_deck_placements for insert
  with check (
    exists (
      select 1 from public.player_decks d
      where d.deck_id = player_deck_placements.deck_id
        and d.player_id = auth.uid()
    )
  );

create policy "player_deck_placements: self update"
  on public.player_deck_placements for update
  using (
    exists (
      select 1 from public.player_decks d
      where d.deck_id = player_deck_placements.deck_id
        and d.player_id = auth.uid()
    )
  );

create policy "player_deck_placements: self delete"
  on public.player_deck_placements for delete
  using (
    exists (
      select 1 from public.player_decks d
      where d.deck_id = player_deck_placements.deck_id
        and d.player_id = auth.uid()
    )
  );

commit;
