-- Add human-readable move description and machine-readable conditional move rules.

begin;

alter table master.m_piece
  add column if not exists move_description_ja text;

create table if not exists master.m_move_pattern_rule (
  move_pattern_rule_id bigint generated by default as identity primary key,
  move_pattern_id bigint not null references master.m_move_pattern(move_pattern_id) on delete cascade,
  rule_type text not null,
  priority smallint not null default 100,
  params_json jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint m_move_pattern_rule_type_chk check (
    rule_type in (
      'path_constraint',
      'state_constraint',
      'turn_parity_override',
      'copy_last_enemy_move',
      'copy_front_enemy_move',
      'target_constraint',
      'immobile',
      'custom'
    )
  ),
  constraint m_move_pattern_rule_priority_chk check (priority >= 0)
);

create unique index if not exists m_move_pattern_rule_unique_active_idx
  on master.m_move_pattern_rule(move_pattern_id, rule_type, priority)
  where is_active = true;

create index if not exists m_move_pattern_rule_lookup_idx
  on master.m_move_pattern_rule(move_pattern_id, is_active, priority);

commit;
