begin;

create table if not exists master.m_skill_implementation_kind (
  implementation_kind text primary key,
  display_name text not null,
  description text not null,
  sort_order smallint not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint m_skill_implementation_kind_sort_order_chk check (sort_order >= 1),
  constraint m_skill_implementation_kind_code_chk check (
    implementation_kind in ('primitive', 'composite', 'script_hook')
  )
);

create table if not exists master.m_skill_schema_group (
  schema_group_id bigint generated by default as identity primary key,
  schema_kind text not null,
  group_code text not null,
  group_name text not null,
  description text,
  sort_order smallint not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint m_skill_schema_group_kind_chk check (
    schema_kind in ('trigger', 'target', 'effect', 'condition', 'param')
  ),
  constraint m_skill_schema_group_sort_order_chk check (sort_order >= 1),
  constraint m_skill_schema_group_kind_group_uq unique (schema_kind, group_code)
);

create table if not exists master.m_skill_schema_option (
  schema_option_id bigint generated by default as identity primary key,
  schema_kind text not null,
  group_code text not null,
  option_code text not null,
  option_name text not null,
  description text,
  validation_json jsonb not null default '{}'::jsonb,
  default_params_json jsonb not null default '{}'::jsonb,
  value_type text,
  is_script_only boolean not null default false,
  sort_order smallint not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint m_skill_schema_option_kind_chk check (
    schema_kind in ('trigger', 'target', 'effect', 'condition', 'param')
  ),
  constraint m_skill_schema_option_sort_order_chk check (sort_order >= 1),
  constraint m_skill_schema_option_kind_option_uq unique (schema_kind, option_code),
  constraint m_skill_schema_option_kind_group_fk
    foreign key (schema_kind, group_code)
    references master.m_skill_schema_group(schema_kind, group_code)
    on delete cascade
);

alter table master.m_skill
  add column if not exists implementation_kind text,
  add column if not exists trigger_group text,
  add column if not exists trigger_type text,
  add column if not exists source_kind text,
  add column if not exists source_file text,
  add column if not exists source_function text,
  add column if not exists tags_json jsonb not null default '[]'::jsonb;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'm_skill_implementation_kind_chk'
  ) then
    alter table master.m_skill
      add constraint m_skill_implementation_kind_chk
      check (
        implementation_kind is null
        or implementation_kind in ('primitive', 'composite', 'script_hook')
      );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'm_skill_source_kind_chk'
  ) then
    alter table master.m_skill
      add constraint m_skill_source_kind_chk
      check (
        source_kind is null
        or source_kind in ('piece_info', 'deck_builder', 'online_battle', 'manual')
      );
  end if;
end
$$;

create index if not exists m_skill_implementation_kind_idx
  on master.m_skill(implementation_kind)
  where implementation_kind is not null;

create index if not exists m_skill_trigger_v2_idx
  on master.m_skill(trigger_group, trigger_type)
  where trigger_group is not null and trigger_type is not null;

alter table master.m_skill_effect
  add column if not exists effect_group text,
  add column if not exists target_group text,
  add column if not exists target_selector text;

create index if not exists m_skill_effect_v2_lookup_idx
  on master.m_skill_effect(effect_group, effect_type, target_group, target_selector);

create table if not exists master.m_skill_condition (
  skill_condition_id bigint generated by default as identity primary key,
  skill_id bigint not null references master.m_skill(skill_id) on delete cascade,
  condition_order smallint not null,
  condition_group text not null,
  condition_type text not null,
  params_json jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint m_skill_condition_order_chk check (condition_order >= 1),
  constraint m_skill_condition_skill_order_uq unique (skill_id, condition_order)
);

create index if not exists m_skill_condition_lookup_idx
  on master.m_skill_condition(condition_group, condition_type);

insert into master.m_skill_implementation_kind (
  implementation_kind,
  display_name,
  description,
  sort_order
)
values
  ('primitive', 'Primitive', '1つの共通実行器で解釈できるスキル', 1),
  ('composite', 'Composite', '複数の primitive effect を順序付きで並べるスキル', 2),
  ('script_hook', 'Script Hook', '共通実行器では表現できず専用実装へ dispatch するスキル', 3)
on conflict (implementation_kind) do update
set
  display_name = excluded.display_name,
  description = excluded.description,
  sort_order = excluded.sort_order,
  is_active = true,
  updated_at = now();

insert into master.m_skill_schema_group (
  schema_kind,
  group_code,
  group_name,
  description,
  sort_order
)
values
  ('trigger', 'event_move', '移動イベント', '自駒の移動に紐づく発火', 1),
  ('trigger', 'event_capture', '捕獲イベント', '駒を取る、または取られることに紐づく発火', 2),
  ('trigger', 'event_turn', 'ターンイベント', 'ターンの境界で評価', 3),
  ('trigger', 'event_other', '他駒イベント', '他の駒の行動に反応して発火', 4),
  ('trigger', 'continuous', '常時評価', '盤面上に存在する限り継続的に評価', 5),
  ('trigger', 'special', '特殊', '共通系に収まらない発火', 6),
  ('target', 'self', '自身', '自分自身を対象に取る', 1),
  ('target', 'adjacent', '隣接', '周囲マスや隣接マスを対象に取る', 2),
  ('target', 'line', '直線', '行、列、正面、左右などの直線系ターゲット', 3),
  ('target', 'board', '盤面', '盤面のマスや位置を直接対象に取る', 4),
  ('target', 'hand', '持ち駒', '持ち駒を対象に取る', 5),
  ('target', 'global', '全体', '盤面全体の駒集合を対象に取る', 6),
  ('target', 'derived', '派生', 'コピー先やユーザー選択など、前段で決まる対象', 7),
  ('effect', 'piece_state', '駒状態', '状態異常、封印、無効化、耐性付与', 1),
  ('effect', 'piece_position', '位置/移動', '位置変更、連動移動、移動ルール変更', 2),
  ('effect', 'piece_lifecycle', '駒ライフサイクル', '消滅、復帰、持ち駒化など', 3),
  ('effect', 'piece_generation', '生成/変化', '召喚、変身、獲得', 4),
  ('effect', 'capture_rule', '捕獲ルール', '取る、取れない、取り方変更', 5),
  ('effect', 'action_economy', '行動経済', '追加行動や2回行動', 6),
  ('effect', 'meta_skill', '能力操作', 'コピーや継承', 7),
  ('effect', 'board_control', '盤面制御', 'マス状態や侵入制限', 8),
  ('effect', 'special', '特殊', '共通化困難な効果', 9),
  ('condition', 'probability', '確率', '乱数発動条件', 1),
  ('condition', 'piece_presence', '駒存在', '特定の駒が存在するかを判定', 2),
  ('condition', 'board_state', '盤面状態', '盤面状況の条件', 3),
  ('condition', 'history', '履歴', '直前手や過去イベントに依存する条件', 4),
  ('condition', 'special', '特殊', '共通条件に収まらないもの', 5),
  ('param', 'probability', '確率', '確率に関するパラメータ', 1),
  ('param', 'duration', '持続', '継続ターンに関するパラメータ', 2),
  ('param', 'range', '範囲', '距離や半径に関するパラメータ', 3),
  ('param', 'count', '件数', '選択数や対象数', 4),
  ('param', 'piece_ref', '駒参照', '生成先や変化先の駒指定', 5),
  ('param', 'movement_rule', '移動規則', '押し出し方や方向など', 6),
  ('param', 'status_rule', '状態規則', '付与する状態異常の種類', 7),
  ('param', 'special', '特殊', '共通パラメータでは表せない引数', 8)
on conflict (schema_kind, group_code) do update
set
  group_name = excluded.group_name,
  description = excluded.description,
  sort_order = excluded.sort_order,
  is_active = true,
  updated_at = now();

insert into master.m_skill_schema_option (
  schema_kind,
  group_code,
  option_code,
  option_name,
  description,
  value_type,
  sort_order,
  is_script_only
)
values
  ('trigger', 'event_move', 'before_move', '移動前', '移動が確定する前に評価', null, 1, false),
  ('trigger', 'event_move', 'after_move', '移動後', '移動完了直後に評価', null, 2, false),
  ('trigger', 'event_capture', 'before_capture', '捕獲前', '捕獲判定前に評価', null, 3, false),
  ('trigger', 'event_capture', 'after_capture', '捕獲後', '自駒が相手駒を取った直後に評価', null, 4, false),
  ('trigger', 'event_capture', 'after_captured', '被捕獲後', '自駒が相手に取られた直後に評価', null, 5, false),
  ('trigger', 'event_turn', 'turn_start', 'ターン開始', '手番開始時に評価', null, 6, false),
  ('trigger', 'event_turn', 'turn_end', 'ターン終了', '手番終了時に評価', null, 7, false),
  ('trigger', 'event_other', 'other_piece_moved', '他駒移動時', '隣接駒や対象駒の移動に反応', null, 8, false),
  ('trigger', 'event_other', 'other_piece_captured', '他駒被捕獲時', '味方または対象駒が取られた時に反応', null, 9, false),
  ('trigger', 'continuous', 'continuous_aura', 'オーラ', '周囲や一定範囲へ継続影響を与える', null, 10, false),
  ('trigger', 'continuous', 'continuous_rule', '自己ルール変更', '自駒自身の移動や捕獲ルールを継続変更する', null, 11, false),
  ('trigger', 'continuous', 'board_state_changed', '盤面変化時再計算', '盤面状態が変わるたびに再評価する', null, 12, false),
  ('trigger', 'special', 'condition_met', '条件成立時', '特定条件の成立そのものを発火点とする', null, 13, false),
  ('trigger', 'special', 'manual_action', '手動発動', 'プレイヤーやAIが明示的に選択して発動する', null, 14, false),
  ('trigger', 'special', 'script_hook', '専用実装', '専用ロジックに委譲する', null, 15, true),
  ('target', 'self', 'self_piece', '自身', '発動した駒自身', null, 1, false),
  ('target', 'adjacent', 'adjacent_enemy', '隣接敵駒', '周囲8マスまたは定義済み隣接範囲の敵駒', null, 2, false),
  ('target', 'adjacent', 'adjacent_ally', '隣接味方駒', '周囲の味方駒', null, 3, false),
  ('target', 'adjacent', 'adjacent_any', '隣接任意駒', '周囲の全駒', null, 4, false),
  ('target', 'adjacent', 'adjacent_empty', '隣接空きマス', '周囲の空きマス', null, 5, false),
  ('target', 'adjacent', 'adjacent_8_enemy', '周囲8敵駒', '周囲8マスの敵駒を明示的に対象化', null, 6, false),
  ('target', 'line', 'left_right_enemy', '左右敵駒', '左右隣接または左右方向の敵駒', null, 7, false),
  ('target', 'line', 'front_enemy', '正面敵駒', '前方に位置する敵駒', null, 8, false),
  ('target', 'line', 'same_row_ally', '同じ行の味方駒', '移動後または現在行に存在する味方駒', null, 9, false),
  ('target', 'line', 'same_row_or_col_ally', '同じ行列の味方駒', '同一行または列に存在する味方駒', null, 10, false),
  ('target', 'board', 'random_board_cell', 'ランダム盤面マス', '盤面全体からランダムに選ぶ', null, 11, false),
  ('target', 'board', 'origin_cell', '移動元マス', '移動前の位置', null, 12, false),
  ('target', 'board', 'destination_cell', '移動先マス', '移動後の位置', null, 13, false),
  ('target', 'board', 'reachable_empty_cell', '到達可能空きマス', '定義済み範囲内の空きマス', null, 14, false),
  ('target', 'hand', 'enemy_hand_random', '敵持ち駒ランダム', '相手の持ち駒からランダム選択', null, 15, false),
  ('target', 'hand', 'ally_hand_random', '味方持ち駒ランダム', '自分の持ち駒からランダム選択', null, 16, false),
  ('target', 'hand', 'ally_hand_piece', '味方持ち駒指定', '自分の持ち駒から条件付きで選択', null, 17, false),
  ('target', 'global', 'all_enemy', '全敵駒', '盤上の敵駒全体', null, 18, false),
  ('target', 'global', 'all_ally', '全味方駒', '盤上の味方駒全体', null, 19, false),
  ('target', 'global', 'all_enemy_high_stroke', '高画数敵駒', '条件に一致する高画数敵駒全体', null, 20, false),
  ('target', 'derived', 'copied_target', 'コピー由来', 'コピー元スキルが解決した対象', null, 21, false),
  ('target', 'derived', 'selected_target', '選択対象', '前段で1体または1マス選択済みの対象', null, 22, false),
  ('target', 'derived', 'script_hook', '専用実装', '共通セレクタでは扱えない対象', null, 23, true),
  ('effect', 'piece_state', 'apply_status', '状態付与', '対象へ状態異常を付与する', null, 1, false),
  ('effect', 'piece_state', 'remove_status', '状態解除', '対象の状態異常を解除する', null, 2, false),
  ('effect', 'piece_state', 'seal_skill', 'スキル封印', '対象のスキル発動を止める', null, 3, false),
  ('effect', 'piece_state', 'disable_piece', '駒無効化', '対象の移動や攻撃を無効化する', null, 4, false),
  ('effect', 'piece_state', 'defense_or_immunity', '防御/無敵', '攻撃回避や特殊効果無効を付与する', null, 5, false),
  ('effect', 'piece_position', 'forced_move', '強制移動', '対象を押し流す、遠ざける、移動させる', null, 6, false),
  ('effect', 'piece_position', 'linked_action', '連携行動', '別駒と連動して動かす', null, 7, false),
  ('effect', 'piece_position', 'reflective_movement', '反射移動', '壁反射など継続移動', null, 8, false),
  ('effect', 'piece_position', 'modify_movement', '移動変更', '移動可能方向や距離を変更する', null, 9, false),
  ('effect', 'piece_lifecycle', 'remove_piece', '駒消滅', '対象駒を盤面から取り除く', null, 10, false),
  ('effect', 'piece_lifecycle', 'return_to_hand', '手駒復帰', '自分の持ち駒へ戻す', null, 11, false),
  ('effect', 'piece_lifecycle', 'destroy_hand_piece', '持ち駒破壊', '持ち駒を除去する', null, 12, false),
  ('effect', 'piece_lifecycle', 'send_to_hand', '持ち駒送り', '対象駒を持ち駒へ送る', null, 13, false),
  ('effect', 'piece_lifecycle', 'revive', '復活', '復活効果を付与または発動する', null, 14, false),
  ('effect', 'piece_lifecycle', 'substitute', '身代わり', '別駒の代わりに処理を受ける', null, 15, false),
  ('effect', 'piece_generation', 'summon_piece', '召喚', '盤面や指定位置に駒を出現させる', null, 16, false),
  ('effect', 'piece_generation', 'transform_piece', '変身/変化', '対象駒を別の駒へ変える', null, 17, false),
  ('effect', 'piece_generation', 'gain_piece', '駒獲得', '持ち駒を増やす', null, 18, false),
  ('effect', 'capture_rule', 'capture_constraint', '捕獲制約', '取れない、味方だけ取れるなどの制約', null, 19, false),
  ('effect', 'capture_rule', 'capture_with_leap', '飛び越え捕獲', '駒をまたいで捕獲する', null, 20, false),
  ('effect', 'capture_rule', 'multi_capture', '複数捕獲', '1手で複数駒を取る', null, 21, false),
  ('effect', 'action_economy', 'extra_action', '追加行動', '追加の移動や行動権を得る', null, 22, false),
  ('effect', 'meta_skill', 'copy_ability', '能力コピー', '別駒の移動やスキルをコピーする', null, 23, false),
  ('effect', 'meta_skill', 'inherit_ability', '能力継承', '元の能力や捕獲対象の能力を継承する', null, 24, false),
  ('effect', 'board_control', 'board_hazard', '盤面ハザード', '毒マス、穴、茨、封鎖マスなどを生成する', null, 25, false),
  ('effect', 'special', 'composite', '複合', '複数effectの束として扱う', null, 26, false),
  ('effect', 'special', 'script_hook', '専用実装', '専用関数へdispatchする', null, 27, true),
  ('condition', 'probability', 'chance_roll', '確率判定', '指定確率で発動する', null, 1, false),
  ('condition', 'piece_presence', 'ally_piece_exists', '味方駒存在', '味方の特定駒が存在する', null, 2, false),
  ('condition', 'piece_presence', 'enemy_piece_exists', '敵駒存在', '敵の特定駒が存在する', null, 3, false),
  ('condition', 'piece_presence', 'same_row_or_col_piece_exists', '同一行列存在', '同じ行または列に特定駒が存在する', null, 4, false),
  ('condition', 'board_state', 'adjacent_enemy_exists', '隣接敵存在', '周囲に敵駒がいる', null, 5, false),
  ('condition', 'board_state', 'adjacent_empty_exists', '隣接空きあり', '周囲に空きマスがある', null, 6, false),
  ('condition', 'board_state', 'target_not_king', '王除外', '対象が王/玉ではない', null, 7, false),
  ('condition', 'history', 'last_enemy_move_exists', '直前敵手あり', '相手の直前手が参照可能', null, 8, false),
  ('condition', 'history', 'captured_by_enemy', '敵に取られた', '敵に捕獲されたことを条件にする', null, 9, false),
  ('condition', 'special', 'script_hook', '専用実装', '専用条件評価へ委譲する', null, 10, true),
  ('param', 'probability', 'procChance', '発動確率', '0.0以上1.0以下', 'number', 1, false),
  ('param', 'duration', 'durationTurns', '持続ターン', '1以上のターン数', 'integer', 2, false),
  ('param', 'range', 'radius', '半径', '中心からの範囲', 'integer', 3, false),
  ('param', 'range', 'distance', '距離', '対象までの距離', 'integer', 4, false),
  ('param', 'count', 'count', '対象数', '対象件数またはall', 'integer_or_all', 5, false),
  ('param', 'count', 'selection', '選択方式', 'random / manual / priority', 'enum', 6, false),
  ('param', 'piece_ref', 'spawnPiece', '召喚駒', '新たに出現させる駒', 'piece_code', 7, false),
  ('param', 'piece_ref', 'transformTo', '変化先', '変化後の駒', 'piece_code', 8, false),
  ('param', 'piece_ref', 'pieceFilter', '駒フィルタ', '対象とする駒種別条件', 'json', 9, false),
  ('param', 'movement_rule', 'movementRule', '移動ルール', 'push_away / pull / random_step / reflect', 'enum', 10, false),
  ('param', 'movement_rule', 'directionRule', '方向ルール', 'front / back / left_right / relative / copied', 'enum', 11, false),
  ('param', 'status_rule', 'statusType', '状態種別', 'freeze / stun / curse / dark / poison / revive', 'enum', 12, false),
  ('param', 'special', 'scriptArgs', '専用引数', 'script_hook専用のJSON', 'json', 13, true)
on conflict (schema_kind, option_code) do update
set
  group_code = excluded.group_code,
  option_name = excluded.option_name,
  description = excluded.description,
  value_type = excluded.value_type,
  sort_order = excluded.sort_order,
  is_script_only = excluded.is_script_only,
  is_active = true,
  updated_at = now();

commit;
