-- Master schema for piece/stage domain (v1).
-- Scope: piece, move pattern, skill, stage, stage-piece relation, initial placement.

create schema if not exists master;

create table if not exists master.m_skill (
  skill_id bigint generated by default as identity primary key,
  skill_code text not null unique,
  skill_name text not null,
  skill_desc text not null,
  trigger_timing text,
  is_active boolean not null default true,
  published_at timestamptz,
  unpublished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint m_skill_publish_window_chk
    check (unpublished_at is null or published_at is null or unpublished_at > published_at)
);

create table if not exists master.m_move_pattern (
  move_pattern_id bigint generated by default as identity primary key,
  move_code text not null unique,
  move_name text not null,
  is_repeatable boolean not null default false,
  can_jump boolean not null default false,
  constraints_json jsonb,
  is_active boolean not null default true,
  published_at timestamptz,
  unpublished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint m_move_pattern_publish_window_chk
    check (unpublished_at is null or published_at is null or unpublished_at > published_at)
);

create table if not exists master.m_move_pattern_vector (
  move_pattern_id bigint not null references master.m_move_pattern(move_pattern_id) on delete cascade,
  dx integer not null,
  dy integer not null,
  max_step integer not null default 1,
  capture_only boolean not null default false,
  move_only boolean not null default false,
  primary key (move_pattern_id, dx, dy, capture_only, move_only),
  constraint m_move_pattern_vector_max_step_chk check (max_step >= 1),
  constraint m_move_pattern_vector_not_zero_chk check (dx <> 0 or dy <> 0),
  constraint m_move_pattern_vector_mode_chk check (not (capture_only and move_only))
);

create table if not exists master.m_piece (
  piece_id bigint generated by default as identity primary key,
  piece_code text not null unique,
  kanji text not null,
  name text not null,
  move_pattern_id bigint not null references master.m_move_pattern(move_pattern_id),
  skill_id bigint references master.m_skill(skill_id),
  is_active boolean not null default true,
  published_at timestamptz,
  unpublished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint m_piece_publish_window_chk
    check (unpublished_at is null or published_at is null or unpublished_at > published_at)
);

create unique index if not exists m_piece_kanji_uq on master.m_piece(kanji);

create table if not exists master.m_stage (
  stage_id bigint generated by default as identity primary key,
  stage_no integer not null unique,
  stage_name text not null,
  unlock_stage_no integer,
  difficulty integer,
  is_active boolean not null default true,
  published_at timestamptz,
  unpublished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint m_stage_stage_no_chk check (stage_no >= 1),
  constraint m_stage_unlock_stage_no_chk check (unlock_stage_no is null or unlock_stage_no < stage_no),
  constraint m_stage_publish_window_chk
    check (unpublished_at is null or published_at is null or unpublished_at > published_at)
);

create table if not exists master.m_stage_piece (
  stage_id bigint not null references master.m_stage(stage_id) on delete cascade,
  piece_id bigint not null references master.m_piece(piece_id),
  role text not null default 'normal',
  weight integer not null default 1,
  primary key (stage_id, piece_id, role),
  constraint m_stage_piece_weight_chk check (weight >= 1),
  constraint m_stage_piece_role_chk check (role in ('normal', 'boss', 'elite', 'support'))
);

create table if not exists master.m_stage_initial_placement (
  stage_id bigint not null references master.m_stage(stage_id) on delete cascade,
  side text not null,
  row_no integer not null,
  col_no integer not null,
  piece_id bigint not null references master.m_piece(piece_id),
  primary key (stage_id, side, row_no, col_no),
  constraint m_stage_initial_placement_side_chk check (side in ('player', 'enemy')),
  constraint m_stage_initial_placement_row_chk check (row_no between 0 and 8),
  constraint m_stage_initial_placement_col_chk check (col_no between 0 and 8)
);

create index if not exists m_stage_piece_piece_id_idx on master.m_stage_piece(piece_id);
create index if not exists m_stage_initial_placement_piece_id_idx on master.m_stage_initial_placement(piece_id);
