-- m_piece_mapping: 駒コード変換の単一ソース
-- piece_code (DB hash) ↔ display_char (game logic: FU/KY/...) ↔ sfen_code (SFEN: P/L/...)
-- このテーブルが唯一の変換ソースとなり、ハードコード変換を撤廃する。

begin;

create table if not exists master.m_piece_mapping (
  id                   bigint generated by default as identity primary key,
  piece_id             bigint not null references master.m_piece(piece_id),
  sfen_code            char(1) check (sfen_code ~ '^[a-zA-Z]$'), -- 標準SFEN 1文字, 特殊駒は NULL
  display_char         text not null,   -- ゲームロジックの表示コード (FU/KY/KE/GI/KI/KA/HI/OU/竜/砲 etc.)
  canonical_piece_code text not null,   -- 正規名 (pawn/lance/.../small_dragon etc.)
  is_special           boolean not null default false,
  is_promoted          boolean not null default false,
  is_active            boolean not null default true,
  priority             integer not null default 0,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  -- display_char の一意性制約（ON CONFLICT ON CONSTRAINT で参照するため通常制約）
  constraint m_piece_mapping_display_char_uq unique (display_char),
  -- sfen_code + is_promoted の一意性制約
  constraint m_piece_mapping_sfen_promoted_uq unique (sfen_code, is_promoted)
);

-- piece_id 検索用インデックス
create index if not exists m_piece_mapping_piece_id_idx
  on master.m_piece_mapping (piece_id);

-- ── Seed: 標準8駒 ──────────────────────────────────────────────────────────

insert into master.m_piece_mapping (
  piece_id,
  sfen_code,
  display_char,
  canonical_piece_code,
  is_special,
  is_promoted,
  is_active,
  created_at,
  updated_at
)
select
  p.piece_id,
  v.sfen_code,
  v.display_char,
  v.canonical_code,
  false,
  false,
  true,
  now(),
  now()
from (
  values
    ('piece_c518b11858f2', 'P', 'FU', 'pawn'),
    ('piece_8bc5d3ca0b32', 'L', 'KY', 'lance'),
    ('piece_7c0b1e09154b', 'N', 'KE', 'knight'),
    ('piece_6e7f7100e7bb', 'S', 'GI', 'silver'),
    ('piece_c8295f7ed9a8', 'G', 'KI', 'gold'),
    ('piece_f221427c3f31', 'B', 'KA', 'bishop'),
    ('piece_cc64bbd54bb3', 'R', 'HI', 'rook'),
    ('piece_cb504254c93f', 'K', 'OU', 'king')
) as v(piece_code, sfen_code, display_char, canonical_code)
join master.m_piece p on p.piece_code = v.piece_code
on conflict on constraint m_piece_mapping_display_char_uq do update
  set sfen_code            = excluded.sfen_code,
      canonical_piece_code = excluded.canonical_piece_code,
      is_active            = true,
      updated_at           = now();

-- ── Seed: 標準成り6駒 ──────────────────────────────────────────────────────

insert into master.m_piece_mapping (
  piece_id,
  sfen_code,
  display_char,
  canonical_piece_code,
  is_special,
  is_promoted,
  is_active,
  created_at,
  updated_at
)
select
  p.piece_id,
  v.sfen_code,
  v.display_char,
  v.canonical_code,
  false,
  true,
  true,
  now(),
  now()
from (
  values
    ('piece_shogi_to', 'P', 'TO', 'prom_pawn'),
    ('piece_shogi_ny', 'L', 'NY', 'prom_lance'),
    ('piece_shogi_nk', 'N', 'NK', 'prom_knight'),
    ('piece_shogi_ng', 'S', 'NG', 'prom_silver'),
    ('piece_shogi_um', 'B', 'UM', 'prom_bishop'),
    ('piece_shogi_ry', 'R', 'RY', 'prom_rook')
) as v(piece_code, sfen_code, display_char, canonical_code)
join master.m_piece p on p.piece_code = v.piece_code
on conflict on constraint m_piece_mapping_display_char_uq do update
  set sfen_code            = excluded.sfen_code,
      canonical_piece_code = excluded.canonical_piece_code,
      is_promoted          = true,
      is_active            = true,
      updated_at           = now();

-- 注意: 特殊駒 (ninja, dragon, cannon 等) は別の migration または seed スクリプトで登録する。
-- 特殊駒は sfen_code = NULL, display_char = kanji (例: '竜', '砲')。

commit;
