-- Runtime game tables for AI matches.
-- Minimal schema for game lifecycle, positions, move history, and inference logs.

begin;

create schema if not exists game;

create table if not exists game.games (
  game_id uuid primary key default gen_random_uuid(),
  player_id uuid not null references public.players(id) on delete restrict,
  stage_id bigint references master.m_stage(stage_id) on delete set null,
  status text not null default 'in_progress',
  result text,
  winner_side text,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint games_status_chk check (status in ('in_progress', 'finished', 'aborted')),
  constraint games_result_chk check (result is null or result in ('player_win', 'enemy_win', 'draw', 'abort')),
  constraint games_winner_side_chk check (winner_side is null or winner_side in ('player', 'enemy')),
  constraint games_end_time_chk check (ended_at is null or ended_at >= started_at)
);

create index if not exists games_player_status_idx on game.games(player_id, status, created_at desc);
create index if not exists games_stage_idx on game.games(stage_id, created_at desc);

create table if not exists game.positions (
  game_id uuid primary key references game.games(game_id) on delete cascade,
  board_state jsonb not null,
  hands jsonb not null default '{}'::jsonb,
  side_to_move text not null,
  turn_number integer not null default 1,
  move_count integer not null default 0,
  sfen text,
  state_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint positions_side_to_move_chk check (side_to_move in ('player', 'enemy')),
  constraint positions_turn_number_chk check (turn_number >= 1),
  constraint positions_move_count_chk check (move_count >= 0)
);

create index if not exists positions_state_hash_idx on game.positions(state_hash);

create table if not exists game.moves (
  move_id bigint generated by default as identity primary key,
  game_id uuid not null references game.games(game_id) on delete cascade,
  move_no integer not null,
  actor_side text not null,
  from_row integer,
  from_col integer,
  to_row integer not null,
  to_col integer not null,
  piece_code text not null,
  promote boolean not null default false,
  drop_piece_code text,
  captured_piece_code text,
  notation text,
  thought_ms integer,
  created_at timestamptz not null default now(),
  constraint moves_game_move_no_uq unique (game_id, move_no),
  constraint moves_actor_side_chk check (actor_side in ('player', 'enemy')),
  constraint moves_from_row_chk check (from_row is null or from_row between 0 and 8),
  constraint moves_from_col_chk check (from_col is null or from_col between 0 and 8),
  constraint moves_to_row_chk check (to_row between 0 and 8),
  constraint moves_to_col_chk check (to_col between 0 and 8),
  constraint moves_move_no_chk check (move_no >= 1),
  constraint moves_thought_ms_chk check (thought_ms is null or thought_ms >= 0),
  constraint moves_drop_semantics_chk check (
    (drop_piece_code is null and from_row is not null and from_col is not null)
    or
    (drop_piece_code is not null and from_row is null and from_col is null)
  )
);

create index if not exists moves_game_idx on game.moves(game_id, move_no);
create index if not exists moves_piece_idx on game.moves(piece_code);

create table if not exists game.ai_inference_logs (
  inference_id bigint generated by default as identity primary key,
  game_id uuid not null references game.games(game_id) on delete cascade,
  move_no integer not null,
  engine_version text not null,
  engine_config jsonb not null,
  request_payload jsonb not null,
  response_payload jsonb not null,
  selected_move text,
  eval_cp integer,
  searched_nodes bigint,
  search_depth integer,
  think_ms integer not null,
  created_at timestamptz not null default now(),
  constraint inference_move_no_chk check (move_no >= 1),
  constraint inference_nodes_chk check (searched_nodes is null or searched_nodes >= 0),
  constraint inference_depth_chk check (search_depth is null or search_depth >= 0),
  constraint inference_think_ms_chk check (think_ms >= 0)
);

create index if not exists inference_game_move_idx on game.ai_inference_logs(game_id, move_no, created_at desc);

commit;
